const ACTION_TYPES = {
  // reading contacts
  GET_CONTACTS_ACTION: 'GET_CONTACTS_ACTION',
  GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',

  // creating contact
  POST_CONTACT_ACTION: 'POST_CONTACT_ACTION',
  POST_CONTACT_REQUEST: 'POST_CONTACT_REQUEST',
  POST_CONTACT_SUCCESS: 'POST_CONTACT_SUCCESS',
  POST_CONTACT_ERROR: 'POST_CONTACT_ERROR',

  // updating contact
  PUT_CONTACT_ACTION: 'PUT_CONTACT_ACTION',
  PUT_CONTACT_REQUEST: 'PUT_CONTACT_REQUEST',
  PUT_CONTACT_SUCCESS: 'PUT_CONTACT_SUCCESS',
  PUT_CONTACT_ERROR: 'PUT_CONTACT_ERROR',

  // deleting contact
  DELETE_CONTACT_ACTION: 'DELETE_CONTACT_ACTION',
  DELETE_CONTACT_REQUEST: 'DELETE_CONTACT_REQUEST',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR',

  CHOOSE_CONTACT: 'CHOOSE_CONTACT',
  SWITCH_MODE_TO_ADD_CONTACT: 'SWITCH_MODE_TO_ADD_CONTACT',
};

export default ACTION_TYPES;
